# version: "3"
# Can remove / comment out the version now because Docker should default to the latest version

services:
  db:
    image: mariadb:10.5
    container_name: namasdre_container
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      # host_port:container_port --> port on your local machine:port inside the Docker container (also 3306 for MySQL)
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namasdre_backend_container
    restart: always
    volumes:
      - ./staticfiles:/app/staticfiles # Mount the static files
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=namasdre_project.settings
    depends_on:
      db:
        condition: service_healthy

volumes:
  data:
    driver: local # This defines the named volume for static files

# In this configuration:we define a volume named static_volume in the top-level volumes section. We use this named volume in the backend service, mapping it to /app/staticfiles in the container.
