# version: "3"
# Can remove / comment out the version now because Docker should default to the latest version

services:
  db:
    image: mariadb:10.5
    container_name: namasdre_container
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      # host_port:container_port --> port on your local machine:port inside the Docker container (also 3306 for MySQL)
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namasdre_backend_container
    command: >
      sh -c "python3 manage.py migrate --noinput &&
             python3 manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles # Volume for static files
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  data:
    driver: local
