# Generated by Django 4.2.10 on 2024-08-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yogaclass",
            options={"permissions": [("manage_classes", "Can manage yoga classes")]},
        ),
    ]
